import { mjdToString } from '../../utility/time';

export default {
  name: 'hiapo',
  path: '/hiapo',
  icon: 'radar-chart',
  defaultLayout: {
    lg: [
      {
        i: 'satellite-simple-hiapo-a',
        x: 0,
        y: 0,
        w: 3,
        h: 7,
        component: {
          name: 'AgentList',
        },
      },
      {
        i: 'satellite-simple-hiapo-ba',
        x: 3,
        y: 0,
        w: 3,
        h: 7,
        component: {
          name: 'DisplayValue',
          props: {
            name: 'hiapo EPS',
            displayValues: [
              {
                name: 'Battery Capacity',
                nodeProcess: 'hiapo:eps',
                dataKey: 'node_battcap',
                unit: 'Whr',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'Battery Percent',
                nodeProcess: 'hiapo:eps',
                dataKey: 'device_batt_percentage_000',
                unit: '%',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'Power Gen',
                nodeProcess: 'hiapo:eps',
                dataKey: 'node_powgen',
                unit: 'W',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'Power Use',
                nodeProcess: 'hiapo:eps',
                dataKey: 'node_powuse',
                unit: 'W',
                processDataKey: (x) => x.toFixed(2),
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-hiapo-b',
        x: 6,
        y: 0,
        w: 3,
        h: 7,
        component: {
          name: 'DisplayValue',
          props: {
            name: 'hiapo CPU',
            displayValues: [
              {
                name: 'CPU Load',
                nodeProcess: 'hiapo:cpu',
                dataKey: 'device_cpu_load_000',
                unit: '',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'CPU Utilization',
                nodeProcess: 'hiapo:cpu',
                dataKey: 'cpu_utilization_000',
                unit: '',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'Max GiB',
                nodeProcess: 'hiapo:cpu',
                dataKey: 'device_cpu_maxgib_000',
                unit: 'GiB',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'GiB',
                nodeProcess: 'hiapo:cpu',
                dataKey: 'device_cpu_gib_000',
                unit: 'GiB',
                processDataKey: (x) => x.toFixed(2),
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-hiapo-c',
        x: 9,
        y: 0,
        w: 3,
        h: 7,
        component: {
          name: 'DisplayValue',
          props: {
            name: 'hiapo Temperature',
            displayValues: [
              {
                name: 'Temp 000',
                nodeProcess: 'hiapo:eps',
                dataKey: 'device_tsen_temp_000',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'Temp 001',
                nodeProcess: 'hiapo:eps',
                dataKey: 'device_tsen_temp_001',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'Temp 002',
                nodeProcess: 'hiapo:eps',
                dataKey: 'device_tsen_temp_002',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'Temp 003',
                nodeProcess: 'hiapo:eps',
                dataKey: 'device_tsen_temp_003',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'EPS OBC CPU Temp',
                nodeProcess: 'hiapo:eps',
                dataKey: 'device_cpu_temp_000',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'Battery Temp',
                nodeProcess: 'hiapo:eps',
                dataKey: 'device_batt_temp_000',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'Temp 000',
                nodeProcess: 'hiapo:eps',
                dataKey: 'device_tsen_temp_000',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'Temp 001',
                nodeProcess: 'hiapo:eps',
                dataKey: 'device_tsen_temp_001',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'Temp 002',
                nodeProcess: 'hiapo:eps',
                dataKey: 'device_tsen_temp_002',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'Temp 003',
                nodeProcess: 'hiapo:eps',
                dataKey: 'device_tsen_temp_003',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'EPS OBC CPU Temp',
                nodeProcess: 'hiapo:eps',
                dataKey: 'device_cpu_temp_000',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'Battery Temp',
                nodeProcess: 'hiapo:eps',
                dataKey: 'device_batt_temp_000',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-hiapo-d',
        x: 0,
        y: 7,
        w: 12,
        h: 10,
        component: {
          name: 'Commands',
          props: {
            nodes: ['cubesat1'],
          },
        },
      },
      {
        i: 'satellite-simple-hiapo-e',
        x: 0,
        y: 8,
        w: 6,
        h: 21,
        component: {
          name: 'Globe',
          props: {
            name: 'Orbit',
            orbits: [
              {
                name: 'hiapo',
                modelFileName: 'cubesat1.glb',
                nodeProcess: 'cubesat1:propagator_simple',
                dataKey: 'node_loc_pos_eci',
                live: true,
                position: [21.289373, 157.917480, 350000.0],
                orientation: {
                  d: {
                    x: 0,
                    y: 0,
                    z: 0,
                  },
                  w: 0,
                },
              },
            ],
            overlays: [
              {
                color: 'CRIMSON',
                geoJson: {
                  type: 'Polygon',
                  coordinates: [
                    [[30, 10], [40, 40], [20, 40], [10, 20], [30, 10]],
                  ],
                },
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-hiapo-f',
        x: 6,
        y: 8,
        w: 6,
        h: 21,
        component: {
          name: 'Attitude',
          props: {
            name: 'Attitude',
            attitudes: [
              {
                name: 'n1',
                nodeProcess: 'cubesat1:propagator_simple',
                dataKey: 'node_loc_att_icrf',
                quaternions: {
                  d: {
                    x: 0,
                    y: 0,
                    z: 0,
                  },
                  w: 0,
                },
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-hiapo-g',
        x: 0,
        y: 3,
        w: 6,
        h: 18,
        component: {
          name: 'Chart',
          props: {
            name: 'CPU',
            XDataKey: 'node_utc',
            processXDataKey: (x) => mjdToString(x),
            plots: [
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'red',
                },
                name: 'Load',
                YDataKey: 'device_cpu_load_000',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:cpu',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'Utilization',
                YDataKey: 'cpu_utilization_000',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:cpu',
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-default-iaa',
        x: 6,
        y: 3,
        w: 6,
        h: 18,
        component: {
          name: 'Chart',
          props: {
            name: 'Thermal',
            XDataKey: 'node_utc',
            processXDataKey: (x) => mjdToString(x),
            plots: [
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'Temp 000',
                YDataKey: 'device_tsen_temp_000',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'orange',
                },
                name: 'Temp 001',
                YDataKey: 'device_tsen_temp_001',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'red',
                },
                name: 'Temp 002',
                YDataKey: 'device_tsen_temp_002',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'yellow',
                },
                name: 'Temp 003',
                YDataKey: 'device_tsen_temp_003',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'green',
                },
                name: 'EPS OBC CPU Temp',
                YDataKey: 'device_cpu_temp_000',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'violet',
                },
                name: 'Battery Temp',
                YDataKey: 'device_batt_temp_000',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-hiapo-hc',
        x: 0,
        y: 4,
        w: 6,
        h: 18,
        component: {
          name: 'Chart',
          props: {
            name: 'EPS Bus Aux',
            XDataKey: 'node_utc',
            processXDataKey: (x) => mjdToString(x),
            plots: [
              {
                x: [],
                y: [],
                type: 'scatter',
                mode: 'marker',
                marker: {
                  color: 'orange',
                },
                name: 'Batt Power',
                YDataKey: 'device_batt_power_000',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'Batt Charge',
                YDataKey: 'device_batt_charge_000',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'green',
                },
                name: 'Batt Percentage',
                YDataKey: 'device_batt_percentage_000',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'purple',
                },
                name: 'Batt Time Remaining',
                YDataKey: 'device_batt_time_remaining_000',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-hiapo-ha',
        x: 6,
        y: 4,
        w: 6,
        h: 18,
        component: {
          name: 'Chart',
          props: {
            name: 'EPS Bus Power',
            XDataKey: 'node_utc',
            processXDataKey: (x) => mjdToString(x),
            plots: [
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'red',
                },
                name: 'Power 000',
                YDataKey: 'device_bus_power_000',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'orange',
                },
                name: 'Power 001',
                YDataKey: 'device_bus_power_001',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'Power 002',
                YDataKey: 'device_bus_power_002',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'gray',
                },
                name: 'Power 003',
                YDataKey: 'device_bus_power_003',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-default-ia',
        x: 0,
        y: 5,
        w: 6,
        h: 18,
        component: {
          name: 'Chart',
          props: {
            name: 'EPS Battery Charge Regulator Power',
            XDataKey: 'node_utc',
            processXDataKey: (x) => mjdToString(x),
            plots: [
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'Power 000',
                YDataKey: 'device_bcreg_power_000',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'orange',
                },
                name: 'Power 001',
                YDataKey: 'device_bcreg_power_001',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'yellow',
                },
                name: 'Power 002',
                YDataKey: 'device_bcreg_power_002',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-default-ja',
        x: 6,
        y: 6,
        w: 6,
        h: 18,
        component: {
          name: 'Chart',
          props: {
            name: 'EPS PDM Switch Power',
            XDataKey: 'node_utc',
            processXDataKey: (x) => mjdToString(x),
            plots: [
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'yellow',
                },
                name: 'Power 000',
                YDataKey: 'device_swch_power_000',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'Power 001',
                YDataKey: 'device_swch_power_001',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'orange',
                },
                name: 'Amp 002',
                YDataKey: 'device_swch_power_002',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'green',
                },
                name: 'Power 003',
                YDataKey: 'device_swch_power_003',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'Power 004',
                YDataKey: 'device_swch_power_004',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'purple',
                },
                name: 'Power 005',
                YDataKey: 'device_swch_power_005',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'red',
                },
                name: 'Power 006',
                YDataKey: 'device_swch_power_006',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'black',
                },
                name: 'Power 007',
                YDataKey: 'device_swch_power_007',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'pink',
                },
                name: 'Amp 008',
                YDataKey: 'device_swch_power_008',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'cyan',
                },
                name: 'Power 009',
                YDataKey: 'device_swch_power_009',
                processYDataKey: (x) => x,
                nodeProcess: 'hiapo:eps',
                live: true,
              },
            ],
          },
        },
      },
    ],
  },
};
