import { mjdToString } from '../../utility/time';

export default {
  name: 'neutron1',
  path: '/neutron1',
  icon: 'qrcode',
  nodes: ['neutron1', 'beagle1'],
  defaultLayout: {
    lg: [
      {
        i: 'satellite-neutron1-a',
        x: 0,
        y: 0,
        w: 3,
        h: 14,
        component: {
          name: 'AgentList',
        },
      },
      {
        i: 'satellite-neutron1-b',
        x: 3,
        y: 0,
        w: 3,
        h: 14,
        component: {
          name: 'Activity',
        },
      },
      {
        i: 'satellite-neutron1-c',
        x: 6,
        y: 0,
        w: 3,
        h: 7,
        component: {
          name: 'DisplayValue',
          props: {
            name: 'CPU',
            displayValues: [
              {
                name: 'CPU Load',
                nodeProcess: 'any',
                dataKey: 'device_cpu_load_000',
                dataKeyUpperThreshold: 1,
                timeDataKey: 'device_cpu_utc_000',
                unit: '',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'CPU Uptime',
                nodeProcess: 'any',
                dataKey: 'device_cpu_uptime_000',
                timeDataKey: 'device_cpu_utc_000',
                unit: 's',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'CPU Boot Count',
                nodeProcess: 'any',
                dataKey: 'device_cpu_boot_count_000',
                timeDataKey: 'device_cpu_utc_000',
                unit: '',
                processDataKey: (x) => x,
              },
              {
                name: 'CPU Load',
                nodeProcess: 'any',
                dataKey: 'device_cpu_load_001',
                dataKeyUpperThreshold: 1,
                timeDataKey: 'device_cpu_utc_001',
                unit: '',
                processDataKey: (x) => x.toFixed(2),
              },
            ],
          },
        },
      },
      {
        i: 'satellite-neutron1-d',
        x: 9,
        y: 0,
        w: 3,
        h: 14,
        component: {
          name: 'DisplayValue',
          props: {
            name: 'Temperature',
            displayValues: [
              {
                name: 'Battery Temp',
                nodeProcess: 'any',
                dataKey: 'device_batt_temp_000',
                timeDataKey: 'device_batt_utc_000',
                unit: 'C',
                dataKeyUpperThreshold: 60,
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'Batt Daughterboard 1 Temp',
                nodeProcess: 'any',
                dataKey: 'device_tsen_temp_000',
                dataKeyUpperThreshold: 60,
                timeDataKey: 'device_tsen_utc_000',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'Batt Daughterboard 2 Temp',
                nodeProcess: 'any',
                dataKey: 'device_tsen_temp_001',
                dataKeyUpperThreshold: 60,
                timeDataKey: 'device_tsen_utc_001',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'Batt Daughterboard 2 Temp',
                nodeProcess: 'any',
                dataKey: 'device_tsen_temp_002',
                dataKeyUpperThreshold: 60,
                timeDataKey: 'device_tsen_utc_002',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'Batt Daughterboard 2 Temp',
                nodeProcess: 'any',
                dataKey: 'device_tsen_temp_003',
                dataKeyUpperThreshold: 60,
                timeDataKey: 'device_tsen_utc_003',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'BBB CPU Temp',
                nodeProcess: 'any',
                dataKey: 'device_cpu_temp_000',
                dataKeyUpperThreshold: 60,
                timeDataKey: 'device_cpu_utc_000',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'EPS DU CPU Temp',
                nodeProcess: 'any',
                dataKey: 'device_cpu_temp_001',
                dataKeyUpperThreshold: 60,
                timeDataKey: 'device_cpu_utc_001',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'CubeComputer CPU Temp',
                nodeProcess: 'any',
                dataKey: 'device_cpu_temp_002',
                dataKeyUpperThreshold: 60,
                timeDataKey: 'device_cpu_utc_002',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'IMU Temp',
                nodeProcess: 'any',
                dataKey: 'device_imu_temp_000',
                dataKeyUpperThreshold: 60,
                timeDataKey: 'device_imu_utc_000',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'Battery Temp',
                nodeProcess: 'any',
                dataKey: 'device_batt_temp_000',
                timeDataKey: 'device_batt_utc_000',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'Batt Daughterboard 1 Temp',
                nodeProcess: 'any',
                dataKey: 'device_tsen_temp_000',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'Batt Daughterboard 2 Temp',
                nodeProcess: 'any',
                dataKey: 'device_tsen_temp_001',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'Batt Daughterboard 2 Temp',
                nodeProcess: 'any',
                dataKey: 'device_tsen_temp_002',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'Batt Daughterboard 2 Temp',
                nodeProcess: 'any',
                dataKey: 'device_tsen_temp_003',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'BBB CPU Temp',
                nodeProcess: 'any',
                dataKey: 'device_cpu_temp_000',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'EPS DU CPU Temp',
                nodeProcess: 'any',
                dataKey: 'device_cpu_temp_001',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'CubeComputer CPU Temp',
                nodeProcess: 'any',
                dataKey: 'device_cpu_temp_002',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'IMU Temp',
                nodeProcess: 'any',
                dataKey: 'device_imu_temp_000',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
            ],
          },
        },
      },
      {
        i: 'satellite-neutron1-e',
        x: 6,
        y: 7,
        w: 3,
        h: 7,
        component: {
          name: 'DisplayValue',
          props: {
            name: 'beagle1 EPS',
            displayValues: [
              {
                name: 'Battery Capacity',
                nodeProcess: 'any',
                dataKey: 'node_battcap',
                timeDataKey: 'node_utc',
                unit: 'Whr',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'Battery Percent',
                nodeProcess: 'any',
                dataKey: 'device_batt_percentage_000',
                dataKeyLowerThreshold: 0.50,
                timeDataKey: 'node_utc',
                unit: '%',
                processDataKey: (x) => x.toFixed(4),
              },
              {
                name: 'Power Gen',
                nodeProcess: 'any',
                timeDataKey: 'node_utc',
                dataKey: 'node_powgen',
                unit: 'W',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'Power Use',
                nodeProcess: 'any',
                timeDataKey: 'node_utc',
                dataKey: 'node_powuse',
                unit: 'W',
                processDataKey: (x) => x.toFixed(2),
              },
            ],
          },
        },
      },
      {
        i: 'satellite-neutron1-f',
        x: 0,
        y: 14,
        w: 6,
        h: 18,
        component: {
          name: 'Chart',
          props: {
            name: 'CPU',
            plots: [
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'red',
                },
                name: 'beagle1 CPU Load',
                YDataKey: 'device_cpu_load_000',
                timeDataKey: 'device_cpu_utc_000',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-default-g',
        x: 6,
        y: 14,
        w: 6,
        h: 18,
        component: {
          name: 'Chart',
          props: {
            name: 'Thermal',
            plots: [
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'Battery Motherboard Temperature',
                YDataKey: 'device_batt_temp_000',
                timeDataKey: 'device_batt_utc_000',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'Battery Daughterboard Temperature 1',
                YDataKey: 'device_tsen_temp_000',
                timeDataKey: 'device_tsen_utc_000',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'orange',
                },
                name: 'Battery Daughterboard 2 Temperature',
                YDataKey: 'device_tsen_temp_001',
                timeDataKey: 'device_tsen_utc_000',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'red',
                },
                name: 'Battery Daughterboard 2 Temperature',
                YDataKey: 'device_tsen_temp_002',
                timeDataKey: 'device_tsen_utc_000',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'yellow',
                },
                name: 'Battery Daughterboard 2 Temperature',
                YDataKey: 'device_tsen_temp_003',
                timeDataKey: 'device_tsen_utc_000',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'yellow',
                },
                name: 'BBB Temperature',
                YDataKey: 'device_cpu_temp_000',
                timeDataKey: 'device_cpu_utc_000',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'green',
                },
                name: 'EPS DU Temperature',
                YDataKey: 'device_cpu_temp_001',
                timeDataKey: 'device_cpu_utc_001',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'green',
                },
                name: 'CubeComputer Temperature',
                YDataKey: 'device_cpu_temp_002',
                timeDataKey: 'device_cpu_utc_002',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'violet',
                },
                name: 'IMU Temperature',
                YDataKey: 'device_imu_temp_000',
                timeDataKey: 'device_imu_utc_0001',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-neutron1-h',
        x: 0,
        y: 32,
        w: 6,
        h: 18,
        component: {
          name: 'Chart',
          props: {
            name: 'EPS Bus Aux',
            XDataKey: 'node_utc',
            processXDataKey: (x) => mjdToString(x),
            plots: [
              {
                x: [],
                y: [],
                type: 'scatter',
                mode: 'marker',
                marker: {
                  color: 'orange',
                },
                name: 'Batt Power',
                YDataKey: 'device_batt_power_000',
                timeDataKey: 'device_batt_utc_000',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'Batt Charge',
                YDataKey: 'device_batt_charge_000',
                timeDataKey: 'device_batt_utc_000',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'green',
                },
                name: 'Batt Percentage',
                YDataKey: 'device_batt_percentage_000',
                timeDataKey: 'device_batt_utc_000',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'purple',
                },
                name: 'Batt Time Remaining',
                YDataKey: 'device_batt_time_remaining_000',
                timeDataKey: 'device_batt_utc_000',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-neutron1-i',
        x: 6,
        y: 32,
        w: 6,
        h: 18,
        component: {
          name: 'Chart',
          props: {
            name: 'EPS Bus Power',
            XDataKey: 'node_utc',
            processXDataKey: (x) => mjdToString(x),
            plots: [
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'red',
                },
                name: 'Power 000',
                YDataKey: 'device_bus_power_000',
                timeDataKey: 'device_bus_utc_000',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'orange',
                },
                name: 'Power 001',
                YDataKey: 'device_bus_power_001',
                timeDataKey: 'device_bus_utc_001',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'Power 002',
                YDataKey: 'device_bus_power_002',
                timeDataKey: 'device_bus_utc_002',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'gray',
                },
                name: 'Power 003',
                YDataKey: 'device_bus_power_003',
                timeDataKey: 'device_bus_utc_003',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-neutron1-j',
        x: 0,
        y: 50,
        w: 6,
        h: 18,
        component: {
          name: 'Chart',
          props: {
            name: 'EPS Battery Charge Regulator Power',
            XDataKey: 'node_utc',
            processXDataKey: (x) => mjdToString(x),
            plots: [
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'Power 000',
                YDataKey: 'device_bcreg_power_000',
                timeDataKey: 'device_bcreg_utc_000',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'orange',
                },
                name: 'Power 001',
                YDataKey: 'device_bcreg_power_001',
                timeDataKey: 'device_bus_utc_001',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'yellow',
                },
                name: 'Power 002',
                YDataKey: 'device_bcreg_power_002',
                timeDataKey: 'device_bcreg_utc_002',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-neutron1-k',
        x: 6,
        y: 50,
        w: 6,
        h: 18,
        component: {
          name: 'Chart',
          props: {
            name: 'EPS PDM Switch Power',
            XDataKey: 'node_utc',
            processXDataKey: (x) => mjdToString(x),
            plots: [
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'yellow',
                },
                name: 'BBB Power',
                YDataKey: 'bbb_power',
                timeDataKey: 'device_swch_utc_000',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'OBC Power',
                YDataKey: 'obc_power',
                timeDataKey: 'device_swch_utc_000',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'orange',
                },
                name: 'Duplex Power',
                YDataKey: 'duplex_power',
                timeDataKey: 'device_swch_utc_000',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'green',
                },
                name: 'TRXVU Power',
                YDataKey: 'trxvu_power',
                timeDataKey: 'device_swch_utc_000',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'green',
                },
                name: 'ASU Power',
                YDataKey: 'asu_power',
                timeDataKey: 'device_swch_utc_000',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-neutron1-l',
        x: 0,
        y: 68,
        w: 12,
        h: 18,
        component: {
          name: 'Chart',
          props: {
            name: 'EPS Power',
            XDataKey: 'node_utc',
            processXDataKey: (x) => mjdToString(x),
            plots: [
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'green',
                },
                name: 'Power Generation',
                YDataKey: 'node_powgen',
                timeDataKey: 'node_utc',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'Power Usage',
                YDataKey: 'node_powuse',
                timeDataKey: 'node_utc',
                processYDataKey: (x) => x,
                nodeProcess: 'any',
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-neutron1-m',
        x: 6,
        y: 86,
        w: 6,
        h: 21,
        component: {
          name: 'Attitude',
          props: {
            name: 'Attitude',
            attitudes: [
              {
                name: 'n1',
                nodeProcess: 'cubesat1:propagator_simple',
                dataKey: 'node_loc_att_icrf',
                quaternions: {
                  d: {
                    x: 0,
                    y: 0,
                    z: 0,
                  },
                  w: 0,
                },
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-neutron1-n',
        x: 0,
        y: 86,
        w: 6,
        h: 21,
        component: {
          name: 'Globe',
          props: {
            name: 'Orbit',
            orbits: [
              {
                name: 'neutron1',
                modelFileName: 'cubesat1.glb',
                nodeProcess: 'cubesat1:propagator_simple',
                dataKey: 'node_loc_pos_eci',
                timeDataKey: 'node_utc',
                live: true,
                position: [21.289373, 157.917480, 350000.0],
                orientation: {
                  d: {
                    x: 0,
                    y: 0,
                    z: 0,
                  },
                  w: 0,
                },
              },
            ],
            overlays: [
              {
                color: 'CRIMSON',
                geoJson: {
                  type: 'Polygon',
                  coordinates: [
                    [[30, 10], [40, 40], [20, 40], [10, 20], [30, 10]],
                  ],
                },
              },
            ],
          },
        },
      },
    ],
  },
  tabs: {
    BBB: {
      lg: [
        {
          i: 'satellite-neutron1-bbb-a',
          x: 0,
          y: 0,
          w: 4,
          h: 7,
          component: {
            name: 'AgentList',
            props: {
              node: 'beagle1',
            },
          },
        },
        {
          i: 'satellite-neutron1-bbb-b',
          x: 4,
          y: 0,
          w: 4,
          h: 7,
          component: {
            name: 'DisplayValue',
            props: {
              name: 'CPU',
              displayValues: [
                {
                  name: 'CPU Load',
                  nodeProcess: 'any',
                  dataKey: 'device_cpu_load_000',
                  timeDataKey: 'device_cpu_utc_000',
                  unit: '',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'CPU Uptime',
                  nodeProcess: 'any',
                  dataKey: 'device_cpu_uptime_000',
                  timeDataKey: 'device_cpu_utc_000',
                  unit: 's',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'CPU Bootcount',
                  nodeProcess: 'any',
                  dataKey: 'device_cpu_boot_count_000',
                  timeDataKey: 'device_cpu_utc_000',
                  unit: '',
                  processDataKey: (x) => x.toFixed(2),
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-bbb-c',
          x: 8,
          y: 0,
          w: 4,
          h: 7,
          component: {
            name: 'DisplayValue',
            props: {
              name: 'Memory',
              displayValues: [
                {
                  name: 'CPU GiB',
                  nodeProcess: 'any',
                  dataKey: 'device_cpu_gib_000',
                  timeDataKey: 'device_cpu_utc_000',
                  unit: '',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'CPU Max GiB',
                  nodeProcess: 'any',
                  dataKey: 'device_cpu_maxgib_000',
                  timeDataKey: 'device_cpu_utc_000',
                  unit: '',
                  processDataKey: (x) => x.toFixed(2),
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-bbb-d',
          x: 0,
          y: 8,
          w: 12,
          h: 18,
          component: {
            name: 'Chart',
            props: {
              name: 'CPU',
              XDataKey: 'device_cpu_utc_000',
              processXDataKey: (x) => mjdToString(x),
              plots: [
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'red',
                  },
                  name: 'beagle1 Load',
                  YDataKey: 'device_cpu_load_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
              ],
            },
          },
        },
      ],
    },
    'ISIS Radio': {
      lg: [

      ],
    },
    'Duplex Radio': {
      lg: [

      ],
    },
    Battery: {
      lg: [
        {
          i: 'satellite-neutron1-batt-a',
          x: 0,
          y: 0,
          w: 9,
          h: 18,
          component: {
            name: 'Chart',
            props: {
              name: 'Battery Temperature',
              plots: [
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'red',
                  },
                  name: 'Motherboard',
                  YDataKey: 'device_batt_temp_000',
                  timeDataKey: 'device_batt_utc_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'orange',
                  },
                  name: 'Daughterboard 1 000',
                  YDataKey: 'device_tsen_temp_000',
                  timeDataKey: 'device_tsen_utc_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Daughterboard 2 001',
                  YDataKey: 'device_tsen_temp_001',
                  timeDataKey: 'device_tsen_utc_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'gray',
                  },
                  name: 'Daughterboard 2 002',
                  YDataKey: 'device_tsen_temp_002',
                  timeDataKey: 'device_tsen_utc_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'yellow',
                  },
                  name: 'Daughterboard 2 003',
                  YDataKey: 'device_tsen_temp_003',
                  timeDataKey: 'device_tsen_utc_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-batt-b',
          x: 9,
          y: 0,
          w: 3,
          h: 7,
          component: {
            name: 'DisplayValue',
            props: {
              name: 'Battery Temperature',
              displayValues: [
                {
                  name: 'Motherboard',
                  nodeProcess: 'any',
                  dataKey: 'device_batt_temp_000',
                  timeDataKey: 'device_batt_utc_000',
                  unit: 'C',
                  processDataKey: (x) => x.toFixed(2),
                  live: true,
                },
                {
                  name: 'Daughterboard 1 000',
                  nodeProcess: 'any',
                  dataKey: 'device_tsen_temp_000',
                  timeDataKey: 'device_batt_utc_000',
                  unit: 'C',
                  processDataKey: (x) => x.toFixed(2),
                  live: true,
                },
                {
                  name: 'Daughterboard 2 001',
                  nodeProcess: 'any',
                  dataKey: 'device_tsen_temp_001',
                  timeDataKey: 'device_batt_utc_000',
                  unit: 'C',
                  processDataKey: (x) => x.toFixed(2),
                  live: true,
                },
                {
                  name: 'Daughterboard 2 002',
                  nodeProcess: 'any',
                  dataKey: 'device_tsen_temp_002',
                  timeDataKey: 'device_batt_utc_000',
                  unit: 'C',
                  processDataKey: (x) => x.toFixed(2),
                  live: true,
                },
                {
                  name: 'Daughterboard 2 003',
                  nodeProcess: 'any',
                  dataKey: 'device_tsen_temp_003',
                  timeDataKey: 'device_batt_utc_000',
                  unit: 'C',
                  processDataKey: (x) => x.toFixed(2),
                  live: true,
                },
              ],
            },
          },
        },
      ],
    },
    Payload: {
      lg: [
        {
          i: 'satellite-neutron1-payload-a',
          x: 0,
          y: 0,
          w: 4,
          h: 7,
          component: {
            name: 'Replacement',
          },
        },
        {
          i: 'satellite-neutron1-payload-b',
          x: 4,
          y: 0,
          w: 4,
          h: 7,
          component: {
            name: 'DisplayValue',
            props: {
              name: 'Payload Power',
              displayValues: [
                {
                  name: 'Power (ADD)',
                  nodeProcess: 'any',
                  dataKey: 'device_cpu_gib_000',
                  timeDataKey: 'device_cpu_utc_000',
                  unit: 'W',
                  processDataKey: (x) => x.toFixed(2),
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-payload-c',
          x: 8,
          y: 0,
          w: 4,
          h: 7,
          component: {
            name: 'DisplayValue',
            props: {
              name: 'Payload Temperature',
              displayValues: [
                {
                  name: 'Temperature (ADD)',
                  nodeProcess: 'any',
                  dataKey: 'device_cpu_gib_000',
                  timeDataKey: 'device_cpu_utc_000',
                  unit: 'C',
                  processDataKey: (x) => x.toFixed(2),
                },
              ],
            },
          },
        },
      ],
    },
    'EPS Battery': {
      lg: [
        {
          i: 'satellite-neutron1-epsbatt-a',
          x: 0,
          y: 0,
          w: 3,
          h: 7,
          component: {
            name: 'DisplayValue',
            props: {
              name: 'EPS Overview',
              displayValues: [
                {
                  name: 'Battery Capacity',
                  nodeProcess: 'any',
                  dataKey: 'node_battcap',
                  timeDataKey: 'node_utc',
                  unit: 'Whr',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Battery Percent',
                  nodeProcess: 'any',
                  dataKey: 'device_batt_percentage_000',
                  dataKeyLowerThreshold: 0.5,
                  timeDataKey: 'node_utc',
                  unit: '%',
                  processDataKey: (x) => x.toFixed(4),
                },
                {
                  name: 'Power Gen',
                  nodeProcess: 'any',
                  timeDataKey: 'node_utc',
                  dataKey: 'node_powgen',
                  unit: 'W',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Power Use',
                  nodeProcess: 'any',
                  timeDataKey: 'node_utc',
                  dataKey: 'node_powuse',
                  unit: 'W',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Battery Temperature',
                  nodeProcess: 'any',
                  dataKey: 'device_batt_temp_000',
                  timeDataKey: 'node_utc',
                  unit: 'C',
                  processDataKey: (x) => (x - 272.15).toFixed(2),
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-tab-epsbatt-b',
          x: 0,
          y: 4,
          w: 6,
          h: 18,
          component: {
            name: 'Chart',
            props: {
              name: 'EPS Bus Amp',
              plots: [
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'red',
                  },
                  name: 'Amp 000',
                  YDataKey: 'device_bus_amp_000',
                  timeDataKey: 'device_bus_utc_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'orange',
                  },
                  name: 'Amp 001',
                  YDataKey: 'device_bus_amp_001',
                  timeDataKey: 'device_bus_utc_001',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Amp 002',
                  YDataKey: 'device_bus_amp_002',
                  timeDataKey: 'device_bus_utc_002',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'gray',
                  },
                  name: '12V Amperage',
                  YDataKey: 'device_bus_amp_003',
                  timeDataKey: 'device_bus_utc_003',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'yellow',
                  },
                  name: 'Batt Amerage',
                  YDataKey: 'device_batt_amp_000',
                  timeDataKey: 'device_batt_utc_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  mode: 'marker',
                  marker: {
                    color: 'red',
                  },
                  name: 'Batt Voltage',
                  YDataKey: 'device_batt_volt_000',
                  timeDataKey: 'device_batt_utc_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-tab-epsbatt-c',
          x: 6,
          y: 4,
          w: 6,
          h: 18,
          component: {
            name: 'Chart',
            props: {
              name: 'EPS Bus Volt',
              plots: [
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'red',
                  },
                  name: 'Volt 000',
                  YDataKey: 'device_bus_volt_000',
                  timeDataKey: 'device_bus_utc_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'orange',
                  },
                  name: 'Volt 001',
                  YDataKey: 'device_bus_volt_001',
                  timeDataKey: 'device_bus_utc_001',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Volt 002',
                  YDataKey: 'device_bus_volt_002',
                  timeDataKey: 'device_bus_utc_002',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'gray',
                  },
                  name: 'Volt 003',
                  YDataKey: 'device_bus_volt_003',
                  timeDataKey: 'device_batt_utc_003',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  mode: 'marker',
                  marker: {
                    color: 'red',
                  },
                  name: 'Batt Voltage',
                  YDataKey: 'device_batt_volt_000',
                  timeDataKey: 'device_batt_utc_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-tab-epsbatt-d',
          x: 0,
          y: 5,
          w: 6,
          h: 18,
          component: {
            name: 'Chart',
            props: {
              name: 'EPS Battery Charge Regulator Amp',
              plots: [
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Amp 000',
                  YDataKey: 'device_bcreg_amp_000',
                  timeDataKey: 'device_bcreg_utc_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'orange',
                  },
                  name: 'Amp 001',
                  YDataKey: 'device_bcreg_amp_001',
                  timeDataKey: 'device_bcreg_utc_001',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'yellow',
                  },
                  name: 'Amp 002',
                  YDataKey: 'device_bcreg_amp_002',
                  timeDataKey: 'device_bcreg_utc_002',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-tab-epsbatt-e',
          x: 6,
          y: 5,
          w: 6,
          h: 18,
          component: {
            name: 'Chart',
            props: {
              name: 'EPS Battery Charge Regulator Volt',
              XDataKey: 'node_utc',
              processXDataKey: (x) => mjdToString(x),
              plots: [
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Volt 000',
                  YDataKey: 'device_bcreg_volt_000',
                  timeDataKey: 'device_bcreg_utc_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'orange',
                  },
                  name: 'Volt 001',
                  YDataKey: 'device_bcreg_volt_001',
                  timeDataKey: 'device_bcreg_utc_001',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'yellow',
                  },
                  name: 'Volt 002',
                  YDataKey: 'device_bcreg_volt_002',
                  timeDataKey: 'device_bcreg_utc_002',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-tab-epsbatt-f',
          x: 0,
          y: 6,
          w: 6,
          h: 19,
          component: {
            name: 'Chart',
            props: {
              name: 'EPS PDM Switch Amp',
              XDataKey: 'node_utc',
              processXDataKey: (x) => mjdToString(x),
              plots: [
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'yellow',
                  },
                  name: 'Amp 000',
                  YDataKey: 'device_swch_amp_000',
                  timeDataKey: 'device_bcreg_utc_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Amp 001',
                  YDataKey: 'device_swch_amp_001',
                  timeDataKey: 'device_bcreg_utc_001',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'orange',
                  },
                  name: 'Amp 002',
                  YDataKey: 'device_swch_amp_002',
                  timeDataKey: 'device_bcreg_utc_002',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'green',
                  },
                  name: 'Amp 003',
                  YDataKey: 'device_swch_amp_003',
                  timeDataKey: 'device_bcreg_utc_003',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Amp 004',
                  YDataKey: 'device_swch_amp_004',
                  timeDataKey: 'device_bcreg_utc_004',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'purple',
                  },
                  name: 'Amp 005',
                  YDataKey: 'device_swch_amp_005',
                  timeDataKey: 'device_bcreg_utc_005',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'red',
                  },
                  name: 'Amp 006',
                  YDataKey: 'device_swch_amp_006',
                  timeDataKey: 'device_bcreg_utc_006',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'black',
                  },
                  name: 'Amp 007',
                  YDataKey: 'device_swch_amp_007',
                  timeDataKey: 'device_bcreg_utc_007',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'pink',
                  },
                  name: 'Amp 008',
                  YDataKey: 'device_swch_amp_008',
                  timeDataKey: 'device_bcreg_utc_008',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'cyan',
                  },
                  name: 'Amp 009',
                  YDataKey: 'device_swch_amp_009',
                  timeDataKey: 'device_bcreg_utc_009',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-tab-epsbatt-g',
          x: 6,
          y: 6,
          w: 6,
          h: 19,
          component: {
            name: 'Chart',
            props: {
              name: 'EPS PDM Switch Volt',
              XDataKey: 'node_utc',
              processXDataKey: (x) => mjdToString(x),
              plots: [
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'yellow',
                  },
                  name: 'Volt 000',
                  YDataKey: 'device_swch_volt_000',
                  timeDataKey: 'device_swch_utc_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Volt 001',
                  YDataKey: 'device_swch_volt_001',
                  timeDataKey: 'device_swch_utc_001',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'orange',
                  },
                  name: 'Volt 002',
                  YDataKey: 'device_swch_volt_002',
                  timeDataKey: 'device_swch_utc_002',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'green',
                  },
                  name: 'Volt 003',
                  YDataKey: 'device_swch_volt_003',
                  timeDataKey: 'device_swch_utc_003',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Volt 004',
                  YDataKey: 'device_swch_volt_004',
                  timeDataKey: 'device_swch_utc_004',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'purple',
                  },
                  name: 'Volt 005',
                  YDataKey: 'device_swch_volt_005',
                  timeDataKey: 'device_swch_utc_005',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'red',
                  },
                  name: 'Volt 006',
                  YDataKey: 'device_swch_volt_006',
                  timeDataKey: 'device_swch_utc_006',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'black',
                  },
                  name: 'Volt 007',
                  YDataKey: 'device_swch_volt_007',
                  timeDataKey: 'device_swch_utc_007',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'pink',
                  },
                  name: 'Volt 008',
                  YDataKey: 'device_swch_volt_008',
                  timeDataKey: 'device_swch_utc_009',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'cyan',
                  },
                  name: 'Volt 009',
                  YDataKey: 'device_swch_volt_009',
                  timeDataKey: 'device_swch_utc_009',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
              ],
            },
          },
        },
      ],
    },
    'EPS Solar Panel': {
      lg: [],
    },
    'EPS Range': {
      lg: [],
    },
    OBC: {
      lg: [
        {
          i: 'satellite-neutron1-obc-a',
          x: 0,
          y: 0,
          w: 4,
          h: 7,
          component: {
            name: 'AgentList',
            props: {
              node: 'neutron1',
            },
          },
        },
        {
          i: 'satellite-neutron1-obc-b',
          x: 4,
          y: 0,
          w: 4,
          h: 7,
          component: {
            name: 'DisplayValue',
            props: {
              name: 'CPU',
              displayValues: [
                {
                  name: 'CPU Load',
                  nodeProcess: 'any',
                  dataKey: 'device_cpu_load_000',
                  timeDataKey: 'device_cpu_utc_000',
                  unit: '',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'CPU Uptime',
                  nodeProcess: 'any',
                  dataKey: 'device_cpu_uptime_000',
                  timeDataKey: 'device_cpu_utc_000',
                  unit: 's',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'CPU Bootcount',
                  nodeProcess: 'any',
                  dataKey: 'device_cpu_boot_count_000',
                  timeDataKey: 'device_cpu_utc_000',
                  unit: '',
                  processDataKey: (x) => x.toFixed(2),
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-obc-c',
          x: 8,
          y: 0,
          w: 4,
          h: 7,
          component: {
            name: 'DisplayValue',
            props: {
              name: 'Memory',
              displayValues: [
                {
                  name: 'CPU GiB',
                  nodeProcess: 'any',
                  dataKey: 'device_cpu_gib_000',
                  timeDataKey: 'device_cpu_utc_000',
                  unit: '',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'CPU Max GiB',
                  nodeProcess: 'any',
                  dataKey: 'device_cpu_maxgib_000',
                  timeDataKey: 'device_cpu_utc_000',
                  unit: '',
                  processDataKey: (x) => x.toFixed(2),
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-obc-d',
          x: 0,
          y: 8,
          w: 12,
          h: 18,
          component: {
            name: 'Chart',
            props: {
              name: 'CPU',
              XDataKey: 'device_cpu_utc_000',
              processXDataKey: (x) => mjdToString(x),
              plots: [
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'red',
                  },
                  name: 'neutron1 Load',
                  YDataKey: 'device_cpu_load_000',
                  timeDataKey: 'device_cpu_utc_001',
                  processYDataKey: (x) => x,
                  nodeProcess: 'any',
                  live: true,
                },
              ],
            },
          },
        },
      ],
    },
    ADCS: {
      lg: [
        {
          i: 'satellite-neutron1-adcs-a',
          x: 0,
          y: 0,
          w: 3,
          h: 7,
          component: {
            name: 'DisplayValue',
            props: {
              name: 'Inertial Measurement Unit',
              displayValues: [
                {
                  name: 'Euler',
                  nodeProcess: 'any',
                  dataKey: 'device_imu_euler_000',
                  timeDataKey: 'device_imu_utc_000',
                  unit: '',
                  processDataKey: (x) => JSON.stringify(x),
                },
                {
                  name: 'Theta',
                  nodeProcess: 'any',
                  dataKey: 'device_imu_euler_000',
                  timeDataKey: 'device_imu_utc_000',
                  unit: '',
                  processDataKey: (x) => JSON.stringify(x),
                },
                {
                  name: 'Omega',
                  nodeProcess: 'any',
                  timeDataKey: 'node_utc',
                  dataKey: 'device_imu_utc_000',
                  unit: '',
                  processDataKey: (x) => x,
                },
                {
                  name: 'Alpha',
                  nodeProcess: 'any',
                  timeDataKey: 'node_utc',
                  dataKey: 'device_imu_utc_000',
                  unit: '',
                  processDataKey: (x) => x,
                },
                {
                  name: 'Mag',
                  nodeProcess: 'any',
                  dataKey: 'device_imu_mag_000',
                  timeDataKey: 'device_imu_utc_000',
                  unit: '',
                  processDataKey: (x) => x,
                },
                {
                  name: 'Bdot',
                  nodeProcess: 'any',
                  dataKey: 'device_imu_bdot_000',
                  timeDataKey: 'device_imu_utc_000',
                  unit: '',
                  processDataKey: (x) => x,
                },
                {
                  name: 'Temperature',
                  nodeProcess: 'any',
                  dataKey: 'device_imu_temp_000',
                  timeDataKey: 'device_imu_utc_000',
                  unit: 'C',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Power',
                  nodeProcess: 'any',
                  dataKey: 'device_imu_power_000',
                  timeDataKey: 'device_imu_utc_000',
                  unit: 'W',
                  processDataKey: (x) => x.toFixed(2),
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-adcs-b',
          x: 3,
          y: 0,
          w: 3,
          h: 7,
          component: {
            name: 'DisplayValue',
            props: {
              name: 'Motor',
              displayValues: [
                {
                  name: 'Momentum 000',
                  nodeProcess: 'any',
                  dataKey: 'device_mtr_mom_000',
                  timeDataKey: 'device_mtr_utc_000',
                  unit: '',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Power 000',
                  nodeProcess: 'any',
                  dataKey: 'device_mtr_power_000',
                  timeDataKey: 'device_mtr_utc_000',
                  unit: 'W',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Momentum 001',
                  nodeProcess: 'any',
                  dataKey: 'device_mtr_mom_001',
                  timeDataKey: 'device_mtr_utc_001',
                  unit: '',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Power 001',
                  nodeProcess: 'any',
                  dataKey: 'device_mtr_power_001',
                  timeDataKey: 'device_mtr_utc_001',
                  unit: 'W',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Momentum 002',
                  nodeProcess: 'any',
                  dataKey: 'device_mtr_mom_002',
                  timeDataKey: 'device_mtr_utc_002',
                  unit: '',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Power 002',
                  nodeProcess: 'any',
                  dataKey: 'device_mtr_power_002',
                  timeDataKey: 'device_mtr_utc_002',
                  unit: 'W',
                  processDataKey: (x) => x.toFixed(2),
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-adcs-c',
          x: 6,
          y: 0,
          w: 3,
          h: 7,
          component: {
            name: 'DisplayValue',
            props: {
              name: 'Reaction Wheel',
              displayValues: [
                {
                  name: 'Omega 000',
                  nodeProcess: 'any',
                  dataKey: 'device_rw_omg_000',
                  timeDataKey: 'device_rw_utc_000',
                  unit: '',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Power 000',
                  nodeProcess: 'any',
                  dataKey: 'device_rw_power_000',
                  timeDataKey: 'device_rw_utc_000',
                  unit: 'W',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Omega 001',
                  nodeProcess: 'any',
                  dataKey: 'device_rw_omg_001',
                  timeDataKey: 'device_rw_utc_001',
                  unit: '',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Power 001',
                  nodeProcess: 'any',
                  dataKey: 'device_rw_power_001',
                  timeDataKey: 'device_rw_utc_001',
                  unit: 'W',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Omega 002',
                  nodeProcess: 'any',
                  dataKey: 'device_rw_omg_002',
                  timeDataKey: 'device_rw_utc_002',
                  unit: '',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Power 002',
                  nodeProcess: 'any',
                  dataKey: 'device_rw_power_002',
                  timeDataKey: 'device_rw_utc_002',
                  unit: 'W',
                  processDataKey: (x) => x.toFixed(2),
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-adcs-d',
          x: 9,
          y: 0,
          w: 3,
          h: 7,
          component: {
            name: 'DisplayValue',
            props: {
              name: 'CPU',
              displayValues: [
                {
                  name: 'Temperature',
                  nodeProcess: 'any',
                  dataKey: 'device_cpu_temp_002',
                  timeDataKey: 'device_cpu_utc_002',
                  unit: 'C',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Power',
                  nodeProcess: 'any',
                  dataKey: 'device_cpu_power_002',
                  timeDataKey: 'device_cpu_utc_002',
                  unit: 'W',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Load',
                  nodeProcess: 'any',
                  dataKey: 'device_cpu_load_002',
                  timeDataKey: 'device_cpu_utc_002',
                  unit: '',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Uptime',
                  nodeProcess: 'any',
                  dataKey: 'device_cpu_uptime_002',
                  timeDataKey: 'device_cpu_utc_002',
                  unit: 's',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Boot Count',
                  nodeProcess: 'any',
                  dataKey: 'device_cpu_boot_count_002',
                  timeDataKey: 'device_cpu_utc_002',
                  unit: '',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Power 002',
                  nodeProcess: 'any',
                  dataKey: 'device_rw_power_002',
                  timeDataKey: 'device_rw_utc_002',
                  unit: 'W',
                  processDataKey: (x) => x.toFixed(2),
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-adcs-e',
          x: 6,
          y: 7,
          w: 6,
          h: 21,
          component: {
            name: 'Attitude',
            props: {
              name: 'Attitude',
              attitudes: [
                {
                  name: 'n1',
                  nodeProcess: 'cubesat1:propagator_simple',
                  dataKey: 'node_loc_att_icrf',
                  quaternions: {
                    d: {
                      x: 0,
                      y: 0,
                      z: 0,
                    },
                    w: 0,
                  },
                  live: true,
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-adcs-f',
          x: 0,
          y: 7,
          w: 6,
          h: 21,
          component: {
            name: 'Globe',
            props: {
              name: 'Orbit',
              orbits: [
                {
                  name: 'neutron1',
                  modelFileName: 'cubesat1.glb',
                  nodeProcess: 'cubesat1:propagator_simple',
                  dataKey: 'node_loc_pos_eci',
                  timeDataKey: 'node_utc',
                  live: true,
                  position: [21.289373, 157.917480, 350000.0],
                  orientation: {
                    d: {
                      x: 0,
                      y: 0,
                      z: 0,
                    },
                    w: 0,
                  },
                },
              ],
              overlays: [
                {
                  color: 'CRIMSON',
                  geoJson: {
                    type: 'Polygon',
                    coordinates: [
                      [[30, 10], [40, 40], [20, 40], [10, 20], [30, 10]],
                    ],
                  },
                },
              ],
            },
          },
        },
      ],
    },
    Commands: {
      lg: [
        {
          i: 'satellite-neutron1-commands-a',
          x: 0,
          y: 0,
          w: 12,
          h: 10,
          component: {
            name: 'MissionEventsDisplay',
            props: {
              nodes: ['neutron1', 'beagle1'],
            },
          },
        },
        {
          i: 'satellite-neutron1-commands-b',
          x: 0,
          y: 10,
          w: 12,
          h: 10,
          component: {
            name: 'Commands',
            props: {
              nodes: ['neutron1', 'beagle1'],
            },
          },
        },
      ],
    },
  },
};
