
#ifndef CUBESAT_DEVICE_TEMPSENSORS
#define CUBESAT_DEVICE_TEMPSENSORS

#include <string>

#define TEMPSENSOR_COUNT 5

#define TEMPSENSOR_EPS_ID 0
#define TEMPSENSOR_OBC_ID 1
#define TEMPSENSOR_PAYLOAD_ID 2
#define TEMPSENSOR_BATT_ID 3
#define TEMPSENSOR_PYCUBED_ID 4

#define TEMPSENSOR_EPS_NAME "temp_eps"
#define TEMPSENSOR_OBC_NAME "temp_obc"
#define TEMPSENSOR_PAYLOAD_NAME "temp_raspi"
#define TEMPSENSOR_BATT_NAME "temp_battery"
#define TEMPSENSOR_PYCUBED_NAME "temp_pycubed"

#define TEMPSENSOR_REGULAR_COUNT 3

#endif
