#!/bin/bash

source config


# Make sure the source directory exists
if [ ! -d "${RASPI_PROJECT_FOLDER}" ]; then
  echo "The source folder ${RASPI_PROJECT_FOLDER} does not exist!"
  exit 1
fi

# Copy the Raspberry Pi project folder to a temporary folder on the BeagleBone
rsync -auv "${RASPI_PROJECT_FOLDER}/" debian@192.168.6.2:/home/debian/cache/raspi

# Check if successful
if [ $? -eq 0 ]; then
    echo "Transferred files to BeagleBone"
else
    echo "Failed to transfer files. Is the BeagleBone connected?"
    exit
fi

# Copy the Raspberry Pi project folder from the temporary folder to the Raspberry Pi
ssh debian@192.168.6.2 rsync -auv /home/debian/cache/raspi/ pi@raspberrypi.local:/home/pi/raspberry-pi

# Check if successful
if [ $? -eq 0 ]; then
    echo "Transferred files to Raspberry Pi"
else
    echo "Failed to transfer files. Is the Raspberry Pi connected?"
fi
