#!/bin/bash

source config

SOURCE_DIR="${BEAGLEBONE_PROJECT_FOLDER}/build/bin/"
DEST_DIR="debian@192.168.6.2:/home/debian/agents"

# Make sure the source directory exists
if [ ! -d "$SOURCE_DIR" ]; then
  echo "The source folder ${SOURCE_DIR} does not exist!"
  exit 1
fi

# Copy the files
rsync -auv ${SOURCE_DIR} ${DEST_DIR}

# Check if successful
if [ $? -eq 0 ]; then
    echo "Success"
else
    echo "Failed to transfer files. Is the BeagleBone connected?"
fi
