#!/bin/bash


source config


SRC_ROUTE_FOLDER=../software/cosmos-web/src/routes
DEST_ROUTE_FOLDER="${COSMOS_WEB_FOLDER}/src/routes"

echo "Updating COSMOS Web routes..."
echo "Source Repository: ${GITHUB_REPO}"
echo "Destination: ${DEST_ROUTE_FOLDER}"


# Check if the destination folder exists
if [ ! -d "$DEST_ROUTE_FOLDER" ]; then
    echo "Fatal: COSMOS Web is not properly installed"
    echo "Exiting now"
    exit
fi

# Check if the route is already installed
if [ -d "$DEST_ROUTE_FOLDER" ]; then
    echo "COSMOS Web routes are already installed."
    read -p "Overwrite existing routes? [y/n]: "
    
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Installation aborted."
        exit
    else
        echo "Removing existing routes"
        rm -rf "$DEST_ROUTE_FOLDER"
    fi
fi




# Copy the repo routes folder to the COSMOS Web routes folder
echo "Copying routes to $DEST_ROUTE_FOLDER..."
cp -R "${SRC_ROUTE_FOLDER}" "$DEST_ROUTE_FOLDER"
echo "Done."

