#!/bin/bash



# Update agents
echo "============================================"
./update-agents -n


# Update COSMOS Web routes
echo "============================================"
./update-routes -n

