#!/bin/bash

source config

echo "Updating Raspberry Pi project..."


# Check if the raspi software is already installed
if [ -d "$RASPI_PROJECT_FOLDER" ]; then
    echo "Raspberry Pi project is already installed."
    read -p "Overwrite existing project? [y/n]: "
    
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Installation aborted."
        exit
    else
        echo "Removing existing project"
        rm -rf "$RASPI_PROJECT_FOLDER"
    fi
fi


# Copy the Raspberry Pi repo folder to the destination folder
echo "Copying Raspberry Pi project to $RASPI_PROJECT_FOLDER..."
cp -R ../software/RaspberryPi "$RASPI_PROJECT_FOLDER"
echo "Done."



