#!/bin/bash

source config

echo "Updating BeagleBone project..."
echo "Destination: ${BEAGLEBONE_PROJECT_FOLDER}"


# Check if the projects folder exists
if [ ! -d "$COSMOS_PROJECT_FOLDER" ]; then
    echo "Fatal: COSMOS is not properly installed"
    echo "Exiting now"
    exit
fi

# Check if the flight software is already installed
if [ -d "$BEAGLEBONE_PROJECT_FOLDER" ]; then
    echo "BeagleBone project is already installed."
    read -p "Overwrite existing project? [y/n]: "
    
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Installation aborted."
        exit
    else
        echo "Removing existing project"
        rm -rf "$BEAGLEBONE_PROJECT_FOLDER"
    fi
fi


# Copy the BeagleBone folder to the COSMOS project folder
echo "Copying BeagleBone project to $BEAGLEBONE_PROJECT_FOLDER..."
cp -R ../software/BeagleBone/beaglebone "$BEAGLEBONE_PROJECT_FOLDER"
echo "Done."



